/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcessoIndexRouteImport } from './routes/acesso.index'
import { Route as AcessoGratisRouteImport } from './routes/acesso.gratis'
import { Route as AcessoPagoRouteImport } from './routes/acesso.pago'
import { Route as AuthenticatedOwnerDashboardRouteImport } from './routes/_authenticated/owner.dashboard'
import { Route as AuthenticatedOwnerMensagensRouteImport } from './routes/_authenticated/owner.mensagens'
import { Route as AuthenticatedOwnerPainelRouteImport } from './routes/_authenticated/owner.painel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoIndexRoute = AcessoIndexRouteImport.update({
  id: '/acesso/',
  path: '/acesso/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoGratisRoute = AcessoGratisRouteImport.update({
  id: '/acesso/gratis',
  path: '/acesso/gratis',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoPagoRoute = AcessoPagoRouteImport.update({
  id: '/acesso/pago',
  path: '/acesso/pago',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOwnerDashboardRoute =
  AuthenticatedOwnerDashboardRouteImport.update({
    id: '/owner/dashboard',
    path: '/owner/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerMensagensRoute =
  AuthenticatedOwnerMensagensRouteImport.update({
    id: '/owner/mensagens',
    path: '/owner/mensagens',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerPainelRoute =
  AuthenticatedOwnerPainelRouteImport.update({
    id: '/owner/painel',
    path: '/owner/painel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/acesso/gratis': typeof AcessoGratisRoute
  '/acesso/pago': typeof AcessoPagoRoute
  '/acesso/': typeof AcessoIndexRoute
  '/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
  '/owner/mensagens': typeof AuthenticatedOwnerMensagensRoute
  '/owner/painel': typeof AuthenticatedOwnerPainelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/acesso/gratis': typeof AcessoGratisRoute
  '/acesso/pago': typeof AcessoPagoRoute
  '/acesso': typeof AcessoIndexRoute
  '/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
  '/owner/mensagens': typeof AuthenticatedOwnerMensagensRoute
  '/owner/painel': typeof AuthenticatedOwnerPainelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/acesso/gratis': typeof AcessoGratisRoute
  '/acesso/pago': typeof AcessoPagoRoute
  '/acesso/': typeof AcessoIndexRoute
  '/_authenticated/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
  '/_authenticated/owner/mensagens': typeof AuthenticatedOwnerMensagensRoute
  '/_authenticated/owner/painel': typeof AuthenticatedOwnerPainelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/acesso/gratis'
    | '/acesso/pago'
    | '/acesso/'
    | '/owner/dashboard'
    | '/owner/mensagens'
    | '/owner/painel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/acesso/gratis'
    | '/acesso/pago'
    | '/acesso'
    | '/owner/dashboard'
    | '/owner/mensagens'
    | '/owner/painel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/acesso/gratis'
    | '/acesso/pago'
    | '/acesso/'
    | '/_authenticated/owner/dashboard'
    | '/_authenticated/owner/mensagens'
    | '/_authenticated/owner/painel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AcessoGratisRoute: typeof AcessoGratisRoute
  AcessoPagoRoute: typeof AcessoPagoRoute
  AcessoIndexRoute: typeof AcessoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso/': {
      id: '/acesso/'
      path: '/acesso'
      fullPath: '/acesso/'
      preLoaderRoute: typeof AcessoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso/gratis': {
      id: '/acesso/gratis'
      path: '/acesso/gratis'
      fullPath: '/acesso/gratis'
      preLoaderRoute: typeof AcessoGratisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso/pago': {
      id: '/acesso/pago'
      path: '/acesso/pago'
      fullPath: '/acesso/pago'
      preLoaderRoute: typeof AcessoPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/owner/dashboard': {
      id: '/_authenticated/owner/dashboard'
      path: '/owner/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof AuthenticatedOwnerDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/mensagens': {
      id: '/_authenticated/owner/mensagens'
      path: '/owner/mensagens'
      fullPath: '/owner/mensagens'
      preLoaderRoute: typeof AuthenticatedOwnerMensagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/painel': {
      id: '/_authenticated/owner/painel'
      path: '/owner/painel'
      fullPath: '/owner/painel'
      preLoaderRoute: typeof AuthenticatedOwnerPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOwnerDashboardRoute: typeof AuthenticatedOwnerDashboardRoute
  AuthenticatedOwnerMensagensRoute: typeof AuthenticatedOwnerMensagensRoute
  AuthenticatedOwnerPainelRoute: typeof AuthenticatedOwnerPainelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOwnerDashboardRoute: AuthenticatedOwnerDashboardRoute,
  AuthenticatedOwnerMensagensRoute: AuthenticatedOwnerMensagensRoute,
  AuthenticatedOwnerPainelRoute: AuthenticatedOwnerPainelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AcessoGratisRoute: AcessoGratisRoute,
  AcessoPagoRoute: AcessoPagoRoute,
  AcessoIndexRoute: AcessoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
