/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcessoIndexRouteImport } from './routes/acesso.index'
import { Route as AcessoGratisRouteImport } from './routes/acesso.gratis'
import { Route as AcessoPagoRouteImport } from './routes/acesso.pago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoIndexRoute = AcessoIndexRouteImport.update({
  id: '/acesso/',
  path: '/acesso/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoGratisRoute = AcessoGratisRouteImport.update({
  id: '/acesso/gratis',
  path: '/acesso/gratis',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoPagoRoute = AcessoPagoRouteImport.update({
  id: '/acesso/pago',
  path: '/acesso/pago',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso/gratis': typeof AcessoGratisRoute
  '/acesso/pago': typeof AcessoPagoRoute
  '/acesso/': typeof AcessoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso/gratis': typeof AcessoGratisRoute
  '/acesso/pago': typeof AcessoPagoRoute
  '/acesso': typeof AcessoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acesso/gratis': typeof AcessoGratisRoute
  '/acesso/pago': typeof AcessoPagoRoute
  '/acesso/': typeof AcessoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/acesso/gratis' | '/acesso/pago' | '/acesso/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/acesso/gratis' | '/acesso/pago' | '/acesso'
  id: '__root__' | '/' | '/acesso/gratis' | '/acesso/pago' | '/acesso/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoGratisRoute: typeof AcessoGratisRoute
  AcessoPagoRoute: typeof AcessoPagoRoute
  AcessoIndexRoute: typeof AcessoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso/': {
      id: '/acesso/'
      path: '/acesso'
      fullPath: '/acesso/'
      preLoaderRoute: typeof AcessoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso/gratis': {
      id: '/acesso/gratis'
      path: '/acesso/gratis'
      fullPath: '/acesso/gratis'
      preLoaderRoute: typeof AcessoGratisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso/pago': {
      id: '/acesso/pago'
      path: '/acesso/pago'
      fullPath: '/acesso/pago'
      preLoaderRoute: typeof AcessoPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoGratisRoute: AcessoGratisRoute,
  AcessoPagoRoute: AcessoPagoRoute,
  AcessoIndexRoute: AcessoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
